# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0004_auto_20180505_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_title',
            field=models.CharField(max_length=80, verbose_name='文章标题'),
        ),
    ]
