# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 22:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0008_auto_20180509_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_createtime'], 'verbose_name': '化妆品'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-t_createtime'], 'verbose_name': '化妆品类别'},
        ),
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='化妆品内容'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_info',
            field=models.CharField(max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_title',
            field=models.CharField(max_length=255, verbose_name='化妆品标题'),
        ),
    ]
